/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutIndexRouteImport } from './routes/_layout.index'
import { Route as LayoutAuditRouteImport } from './routes/_layout.audit'
import { Route as LayoutBookingOccupancyRouteImport } from './routes/_layout.booking-occupancy'
import { Route as LayoutCancellationRiskRouteImport } from './routes/_layout.cancellation-risk'
import { Route as LayoutComplaintsRouteImport } from './routes/_layout.complaints'
import { Route as LayoutInsightsRouteImport } from './routes/_layout.insights'
import { Route as LayoutPricingRouteImport } from './routes/_layout.pricing'
import { Route as LayoutRecommendationsRouteImport } from './routes/_layout.recommendations'
import { Route as LayoutResort360RouteImport } from './routes/_layout.resort-360'
import { Route as LayoutRooms360RouteImport } from './routes/_layout.rooms-360'
import { Route as LayoutSettingsRouteImport } from './routes/_layout.settings'
import { Route as LayoutStaffRouteImport } from './routes/_layout.staff'
import { Route as LayoutTasksRouteImport } from './routes/_layout.tasks'
import { Route as LayoutVerificationRouteImport } from './routes/_layout.verification'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAuditRoute = LayoutAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBookingOccupancyRoute = LayoutBookingOccupancyRouteImport.update({
  id: '/booking-occupancy',
  path: '/booking-occupancy',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCancellationRiskRoute = LayoutCancellationRiskRouteImport.update({
  id: '/cancellation-risk',
  path: '/cancellation-risk',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutComplaintsRoute = LayoutComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutInsightsRoute = LayoutInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPricingRoute = LayoutPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRecommendationsRoute = LayoutRecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutResort360Route = LayoutResort360RouteImport.update({
  id: '/resort-360',
  path: '/resort-360',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRooms360Route = LayoutRooms360RouteImport.update({
  id: '/rooms-360',
  path: '/rooms-360',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutStaffRoute = LayoutStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTasksRoute = LayoutTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutVerificationRoute = LayoutVerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/audit': typeof LayoutAuditRoute
  '/booking-occupancy': typeof LayoutBookingOccupancyRoute
  '/cancellation-risk': typeof LayoutCancellationRiskRoute
  '/complaints': typeof LayoutComplaintsRoute
  '/insights': typeof LayoutInsightsRoute
  '/pricing': typeof LayoutPricingRoute
  '/recommendations': typeof LayoutRecommendationsRoute
  '/resort-360': typeof LayoutResort360Route
  '/rooms-360': typeof LayoutRooms360Route
  '/settings': typeof LayoutSettingsRoute
  '/staff': typeof LayoutStaffRoute
  '/tasks': typeof LayoutTasksRoute
  '/verification': typeof LayoutVerificationRoute
}
export interface FileRoutesByTo {
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/audit': typeof LayoutAuditRoute
  '/booking-occupancy': typeof LayoutBookingOccupancyRoute
  '/cancellation-risk': typeof LayoutCancellationRiskRoute
  '/complaints': typeof LayoutComplaintsRoute
  '/insights': typeof LayoutInsightsRoute
  '/pricing': typeof LayoutPricingRoute
  '/recommendations': typeof LayoutRecommendationsRoute
  '/resort-360': typeof LayoutResort360Route
  '/rooms-360': typeof LayoutRooms360Route
  '/settings': typeof LayoutSettingsRoute
  '/staff': typeof LayoutStaffRoute
  '/tasks': typeof LayoutTasksRoute
  '/verification': typeof LayoutVerificationRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/_layout/audit': typeof LayoutAuditRoute
  '/_layout/booking-occupancy': typeof LayoutBookingOccupancyRoute
  '/_layout/cancellation-risk': typeof LayoutCancellationRiskRoute
  '/_layout/complaints': typeof LayoutComplaintsRoute
  '/_layout/insights': typeof LayoutInsightsRoute
  '/_layout/pricing': typeof LayoutPricingRoute
  '/_layout/recommendations': typeof LayoutRecommendationsRoute
  '/_layout/resort-360': typeof LayoutResort360Route
  '/_layout/rooms-360': typeof LayoutRooms360Route
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/staff': typeof LayoutStaffRoute
  '/_layout/tasks': typeof LayoutTasksRoute
  '/_layout/verification': typeof LayoutVerificationRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/landing'
    | '/login'
    | '/audit'
    | '/booking-occupancy'
    | '/cancellation-risk'
    | '/complaints'
    | '/insights'
    | '/pricing'
    | '/recommendations'
    | '/resort-360'
    | '/rooms-360'
    | '/settings'
    | '/staff'
    | '/tasks'
    | '/verification'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/landing'
    | '/login'
    | '/audit'
    | '/booking-occupancy'
    | '/cancellation-risk'
    | '/complaints'
    | '/insights'
    | '/pricing'
    | '/recommendations'
    | '/resort-360'
    | '/rooms-360'
    | '/settings'
    | '/staff'
    | '/tasks'
    | '/verification'
    | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/landing'
    | '/login'
    | '/_layout/audit'
    | '/_layout/booking-occupancy'
    | '/_layout/cancellation-risk'
    | '/_layout/complaints'
    | '/_layout/insights'
    | '/_layout/pricing'
    | '/_layout/recommendations'
    | '/_layout/resort-360'
    | '/_layout/rooms-360'
    | '/_layout/settings'
    | '/_layout/staff'
    | '/_layout/tasks'
    | '/_layout/verification'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LandingRoute: typeof LandingRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/audit': {
      id: '/_layout/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof LayoutAuditRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/booking-occupancy': {
      id: '/_layout/booking-occupancy'
      path: '/booking-occupancy'
      fullPath: '/booking-occupancy'
      preLoaderRoute: typeof LayoutBookingOccupancyRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/cancellation-risk': {
      id: '/_layout/cancellation-risk'
      path: '/cancellation-risk'
      fullPath: '/cancellation-risk'
      preLoaderRoute: typeof LayoutCancellationRiskRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/complaints': {
      id: '/_layout/complaints'
      path: '/complaints'
      fullPath: '/complaints'
      preLoaderRoute: typeof LayoutComplaintsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/insights': {
      id: '/_layout/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof LayoutInsightsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/pricing': {
      id: '/_layout/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof LayoutPricingRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/recommendations': {
      id: '/_layout/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof LayoutRecommendationsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/resort-360': {
      id: '/_layout/resort-360'
      path: '/resort-360'
      fullPath: '/resort-360'
      preLoaderRoute: typeof LayoutResort360RouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/rooms-360': {
      id: '/_layout/rooms-360'
      path: '/rooms-360'
      fullPath: '/rooms-360'
      preLoaderRoute: typeof LayoutRooms360RouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/staff': {
      id: '/_layout/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof LayoutStaffRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/tasks': {
      id: '/_layout/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof LayoutTasksRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/verification': {
      id: '/_layout/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof LayoutVerificationRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAuditRoute: typeof LayoutAuditRoute
  LayoutBookingOccupancyRoute: typeof LayoutBookingOccupancyRoute
  LayoutCancellationRiskRoute: typeof LayoutCancellationRiskRoute
  LayoutComplaintsRoute: typeof LayoutComplaintsRoute
  LayoutInsightsRoute: typeof LayoutInsightsRoute
  LayoutPricingRoute: typeof LayoutPricingRoute
  LayoutRecommendationsRoute: typeof LayoutRecommendationsRoute
  LayoutResort360Route: typeof LayoutResort360Route
  LayoutRooms360Route: typeof LayoutRooms360Route
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutStaffRoute: typeof LayoutStaffRoute
  LayoutTasksRoute: typeof LayoutTasksRoute
  LayoutVerificationRoute: typeof LayoutVerificationRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAuditRoute: LayoutAuditRoute,
  LayoutBookingOccupancyRoute: LayoutBookingOccupancyRoute,
  LayoutCancellationRiskRoute: LayoutCancellationRiskRoute,
  LayoutComplaintsRoute: LayoutComplaintsRoute,
  LayoutInsightsRoute: LayoutInsightsRoute,
  LayoutPricingRoute: LayoutPricingRoute,
  LayoutRecommendationsRoute: LayoutRecommendationsRoute,
  LayoutResort360Route: LayoutResort360Route,
  LayoutRooms360Route: LayoutRooms360Route,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutStaffRoute: LayoutStaffRoute,
  LayoutTasksRoute: LayoutTasksRoute,
  LayoutVerificationRoute: LayoutVerificationRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LandingRoute: LandingRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
